### ISSUE TITLE
App crashes when generating encryption keys

### ISSUE THREAD

**Issue by svprdga** [ente-io/frame#11]
The app is crashing on my device when generating the encryption keys.
Model: Samsung Galaxy A3 2017

### Steps to reproduce

- Run app in the provided device
- Wait for the generation phase

### Expected result

- The app generates the keys successfully and continues the flow.

### Actual result

- The app crashes (it is a native crash, not from the flutter side)

### Notes

I have tried to debug the error, but when I try to run the app I got this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processPlaystoreDebugResources'.
> Could not resolve all task dependencies for configuration ':app:playstoreDebugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/svprdga/.m2/repository/com/transistorsoft/tsbackgroundfetch/
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/svprdga/code/personal/flutter/samples/frame/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 14s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by vishnukvmd** [comment]
Hey, sorry about the build failure.

We had split our build steps in an attempt to make things FDroid friendly. Could you please pull `master` once and retry?

The following command should start the app up on your device.
```
flutter run --flavor independent --release
```
It would be great if you could share the logs post this. Thanks again!

**Comment by svprdga** [comment]
Hi, I am having problems running the app with the command you provided to me:

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalIndependentRelease'.           
> Could not resolve all artifacts for configuration ':app:playstoreReleaseRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/svprdga/code/personal/flutter/samples/frame/build/app/intermediates/flutter/playstoreRelease/libs.jar.
         > Transform's input file does not exist: /home/svprdga/code/personal/flutter/samples/frame/build/app/intermediates/flutter/playstoreRelease/libs.jar. (See https://issuetracker.google.com/issues/158753935)
```

I have also tried in debug, but it shows an error when trying to log-in.

**Comment by vishnukvmd** [comment]
Looks like it's trying to find a PlayStore variant. Could you first run
```
flutter build --flavor playstore --release
```

Or maybe just try to run the PlayStore build?
```
flutter run --flavor playstore --release
```

**Comment by svprdga** [comment]
I could finally run the app with `flutter run --flavor playstore --release`

Unfortunately I could create successfully the keys...this sounds maybe a minification issue? Sometime ago it happened to me that a crash only occurred when running the compiled and signed APK.

I suggest you to add some kind of crash logging, for instance ACRA (it respects privacy).

**Comment by vishnukvmd** [comment]
I'm glad that the app is running now!

That said, `flutter run --flavor {independent | playstore} --release` is the command we use to generate our release builds, so I'm not sure why things are magically working now. 

Could you tell me if you installed the broken build from PlayStore or from our GitHub releases?

In the meanwhile, I'll dig through the reports on our self-hosted sentry (which is kind of like ACRA) and see if there is a crash log there.

**Comment by svprdga** [comment]
I installed the app directly through Play Store. Now, after setting up the keys via my own build, I have downloaded the 'officially' signed app from Google Play and until now everything is working fine.

**Comment by vishnukvmd** [comment]
https://github.com/firstfloorsoftware/flutter_sodium/pull/63 fixes it. For now I've taken a local dependency on the library. I'll update to the published version once the PR is merged.
