### ISSUE TITLE
(iOS) App doesn't go past "grant permission" screen

### ISSUE THREAD

**Issue by rootedetc** [ente-io/frame#13]
The app asks for permission to access my photos, and upon choosing "Select photos" or denying the permission, the app won't go any further than that screen.

**Comment by vishnukvmd** [comment]
We've discovered an issue with iOS's "limited permissions" API.  Sorry for the trouble, and thank you for reporting this.

We'll incorporate a fix and update this issue.

**Comment by vishnukvmd** [comment]
A build with a fix has been submitted to AppStore for review.

_GitHub auto closed the issue when the PR was merged. I'll manually close this once the release is live._

**Comment by vishnukvmd** [comment]
The build has been approved, please update from here: https://apps.apple.com/in/app/ente-photos/id1542026904

Thanks again for reporting this, and sorry for the troubles.
