### ISSUE TITLE
"duplicate files" tool freezing and crashing app

### ISSUE THREAD

**Issue by seanfrasure** [ente-io/frame#159]
When I try to see my duplicate files the app freezes and (usually) crashes about 30 seconds later. It gets stuck with the loader (screenshot below) and still happens even when there is no active uploading/syncing. For context, I have about 16 GB of data stored.

iPhone XR, iOS 15.0.2
App version 0.4.6
![image](https://user-images.githubusercontent.com/9723817/147978687-78669198-22eb-4cfb-9762-01ff08c327ee.png)

Log of last few mins before crash: https://www.toptal.com/developers/hastebin/ojuzexagem.yaml

**Comment by vishnukvmd** [comment]
@seanfrasure Thanks for reporting this! Looks like the library we use for logging was the culprit. 😕

This has been fixed and an update has been submitted to AppStore. Sorry that you ran into this!

I'll close this issue once the update is live.

**Comment by seanfrasure** [comment]
Awesome, thank you for being on it so quickly!

**Comment by vishnukvmd** [comment]
@seanfrasure The build is now live: [AppStore](https://apps.apple.com/in/app/ente-photos/id1542026904).

Please reopen this issue if you are unhappy! 😄
