### ISSUE TITLE
[Feature request] Search in mobile apps

### ISSUE THREAD

**Issue by 0frasure** [ente-io/frame#180]
I think that it would be very useful to have this same search feature that is in the web/desktop client.

![image](https://user-images.githubusercontent.com/9723817/152446118-9724a8ff-6d2a-4b9d-9a0d-1c8b8e75332d.png)

**Comment by vishnukvmd** [comment]
Thanks for bringing this up @seanfrasure! This is already in the works, will update this issue once we ship the feature.

**Comment by seanfrasure** [comment]
@vishnukvmd That's great, I can't wait! Will there also be image recognition in the future too?

**Comment by vishnukvmd** [comment]
We've made quite a bit of progress on desktop. We'll port the implementation to mobile after we are satisfied with its accuracy.

Could you please subscribe to [r/enteio](https://reddit.com/r/enteio)? We'll be launching a beta program there soon and would love to have your feedback!

**Comment by seanfrasure** [comment]
> Could you please subscribe to [r/enteio](https://reddit.com/r/enteio)? We'll be launching a beta program there soon and would love to have your feedback!

Done, thank you!
