### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [ente-io/frame#2]
...is a milestone somewhere? :)

Ref: https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by vishnukvmd** [comment]
Have created an issue: https://gitlab.com/fdroid/rfp/-/issues/1742

**Comment by aliasav** [comment]
created MR to fdroid repo: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9022

**Comment by ua741** [comment]
@licaon-kter  Unfortunately, flutter doesn't support selectively adding dependency based on build flavor. Is it acceptable if we maintain a separate branch for f-droid? 

PS: We are able to build the project without any dependency on libraries for Google Payments & Firebase.

**Comment by licaon-kter** [comment]
Fine for F-Droid, hope it's not too much work :)

**Comment by ua741** [comment]
> Fine for F-Droid, hope it's not too much work :)

For reference, we have created a draft MR here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10942
