### ISSUE TITLE
iOS photo crops are not preserved when uploaded to Ente

### ISSUE THREAD

**Issue by Andrew-Finn** [ente-io/frame#224]
When using the Ente iOS app any crops made via iOS photos app or at time of capture using the iOS screenshot UI are reverted when uploaded to Ente.

Steps to reproduce:
- On iOS take screenshot and crop the image as desired
- Backup to Ente
- Use Ente to free up space on local device and clear cache
- Ente image will now default back to the uncropped image

Thanks!

**Comment by ua741** [comment]
Hey @Andrew-Finn, 

Thank you share reporting this issue and sharing the steps to reproduce it. We have identified a potential issue. Hopefully, we will put out a release with the fix by the end of this week. We will update here once the release is available on the app store.

~ Neeraj

**Comment by ua741** [comment]
Hey @Andrew-Finn ,

This issue is fixed in the latest release of our iOS app. 
Please feel free to comment on this issue or create new issue if you face this issue again.

Thank you again for reporting this. 

~ Neeraj
