### ISSUE TITLE
firebase in F-Droid build

### ISSUE THREAD

**Issue by linsui** [ente-io/frame#411]
https://github.com/ente-io/frame/blob/17f1de69e6b4f1ee7d0bf3a390e8eb98ef298a47/pubspec.yaml#L50 Could you please fix it? Thanks!

**Comment by ua741** [comment]
[Fixed](https://github.com/ente-io/frame/blob/f-droid/pubspec.yaml#L47). Thank you for flagging it.

**Comment by licaon-kter** [comment]
And again? https://github.com/ente-io/photos-app/blob/fdroid-0.7.65/pubspec.yaml#L52-L53

ref: https://monitor.f-droid.org/builds/log/io.ente.photos.fdroid/464#site-footer

**Comment by ua741** [comment]
@licaon-kter Thank you for flagging this. Seems like we ended up shipping the dependency, although the code for initialising Firebase related handlers was still commented out. 
We add safe-guards during commit and tagging to ensure that this doesn't happen again.

**Comment by ua741** [comment]
Have added a pre-commit hook to ensure that this doesn't happen again.
