### ISSUE TITLE
[Documentation] File French ANSSI declaration

### ISSUE THREAD

**Issue by mnvr** [ente-io/frame#452]
We'll submit encryption control application to France's ANSSI. This is just a note for what we needed to do, for future reference.

## Overview

To distribute the app on the French app store, we need to submit an encryption declaration to the French government and then upload their acknowledgment to the app store.

## Why

We need to do this if 

> Your app uses an industry standard algorithm, not provided within the Apple operating system

<img width="759" alt="Screenshot 2022-08-29 at 6 55 10 PM" src="https://user-images.githubusercontent.com/24503581/187211704-1c178e9f-0ab7-470b-8660-d38ab70dda9d.png">

https://help.apple.com/app-store-connect/#/devc3f64248f

Similar to US (See https://github.com/ente-io/frame/issues/427), the French government also controls the import and export of encryption apps distributed in France.

## Submitting an application

- Instructions and the form are at https://www.ssi.gouv.fr/en/regulation/cryptology/how-to-submit-an-application/

- The PDF is in French, but for the answers "English is tolerated" (!).

- Email needs to be sent to "controle[at]ssi.gouv.fr"

- Subject should be "[formalités] brand – name of the item". 

## Similar issues

- https://github.com/status-im/status-mobile/issues/4109

**Comment by SkypLabs** [comment]
If you need one day the help of a French speaker for your paperwork, don't hesitate to ping me. I'd be happy to give you a hand.
