### ISSUE TITLE
F-Droid - APK parsing issue when installing

### ISSUE THREAD

**Issue by SkypLabs** [ente-io/frame#615]
Hi,

I've got the following error when trying to install the latest version of ente (0.6.51) on my Android phone from F-Droid:

![_20221102_183844.JPG](https://user-images.githubusercontent.com/9932586/199562035-b227ffc4-3b23-4732-973f-3c903d12e861.JPG)

I run on Android 12.

I'll have a look at the logs and paste them here.

Thank you for your help.

**Comment by vishnukvmd** [comment]
Hey! We've already published a [fix](https://github.com/ente-io/frame/commit/2b5b8edadc44adabcb851f1307ce0b647d49edbb) for this to F-Droid, and are waiting for their build servers to pick up the changes. Will update this thread once the build is live :)

**Comment by SkypLabs** [comment]
Awesome! Thanks for your quick answer.

I'll keep this issue open to let you know if the fix worked out as expected once available on F-Droid.

**Comment by vishnukvmd** [comment]
@SkypLabs The new build is now live on F-Droid: [https://f-droid.org/packages/io.ente.photos.fdroid/](https://f-droid.org/packages/io.ente.photos.fdroid/).

Please let us know if all is well 😊

**Comment by SkypLabs** [comment]
Yes it worked 👌 I just installed it.

Thanks again for your help and keep up the great work 🚀
